sudo: required
services:
- docker
language: scala
scala:
- 2.12.2
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.cache/.coursier"
script:
- sudo mkdir .sbt
- sudo mkdir dist
- docker-compose run book npm install
- docker-compose run book ./sbt.sh pdf html epub ; export SBT_RESULT=$?
- test "$SBT_RESULT" == "0"
after_success:
- "./deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_6be077f829fc_key -iv $encrypted_6be077f829fc_iv
  -in book_deploy_rsa.enc -out book_deploy_rsa -d
